version: '3.9'

services:
    vue-app:
        container_name: vue-app
        build:
            context: .
            dockerfile: Dockerfile
        ports:
            - '8080:8080'
        volumes:
            - ./:/home/app
            - /home/app/node_modules